//Auth
export const USER_LOADED = "USER_LOADED";
export const USER_LOADED_FAIL = "USER_LOADED_FAIL";
export const CLEAR_PROFILE = "CLEAR_PROFILE";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const ACCOUNT_DELETED = "ACCOUNT_DELETED";
export const LOGOUT = "LOGOUT";

export const AUTH_ERROR = "AUTH_ERROR";
export const RECOVER_REQUEST_SUCCESS = "RECOVER_REQUEST_SUCCESS";
export const RECOVER_REQUEST_FAILED = "RECOVER_REQUEST_FAILED";
export const PASSWORD_CHANGED = "PASSWORD_CHANGED";
export const PASSWORD_CHANGE_FAIL = "PASSWORD_CHANGE_FAIL";

//ALERT
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
